language: node_js
node_js:
  - 0.10
env:
  - DISPLAY=:99.0
addons:
  firefox: "28.0"
before_script:
  - "sh -e /etc/init.d/xvfb start"
deploy:
  provider: npm
  email: christoph.burgmer@gmail.com
  api_key:
    secure: EsvyCKvVOxMZDU5yvIGiwpqWTGlHUWZtcFLTaXqdJB4PseJQpDoWohFL+aH/N3cc5DgxwtCTRunwQ1jesGsQb++AWMZ5TeWuYDQXvvU6vs5oGY7wChqb70Ksjbcyp4MIzyUEotfwt+PGlDKPEOb/S3wnBBRjF9m5fWfnS4RjVZQ=
  on:
    tags: true
    repo: cburgmer/rasterizeHTML.js
branches:
  only:
    - master
